# GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_x32
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),release_x32)
  RESCOMP = windres
  TARGETDIR = ../../bin
  TARGET = $(TARGETDIR)/gm_roc_linux.dll
  OBJDIR = obj
  DEFINES += -DNDEBUG -DGMMODULE -DVERSION_SAFE_STEAM_API_INTERFACES -DVECTOR -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -DRAD_TELEMETRY_DISABLED -DPROTECTED_THINGS_ENABLE -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DNO_MALLOC_OVERRIDE
  INCLUDES += -I../../../../source-sdk-2013/mp/src/public -I../../../../source-sdk-2013/mp/src/public/engine -I../../../../source-sdk-2013/mp/src/common -I../../../../source-sdk-2013/mp/src/public/vstdlib -I../../../../source-sdk-2013/mp/src/public/steam -I../../../../source-sdk-2013/mp/src/public/tier0 -I../../../../source-sdk-2013/mp/src/public/tier1 -I../../../../source-sdk-2013/mp/src/tier1 -I../../../../source-sdk-2013/mp/src/public/game/server -I../../../../source-sdk-2013/mp/src/game/shared -I../../../../source-sdk-2013/mp/src/game/server -I../../../../source-sdk-2013/mp/src/game/client -I../../../../gmod-module-base/include -I../../includes
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g -O2 -fPIC -msse2
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CFLAGS)
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lsteam_api -lrt -ldl
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -L../../../../source-sdk-2013/mp/src/lib/public/linux32 -L../../../../source-sdk-2013/mp/src/lib/linux32 -L../../../../source-sdk-2013/mp/src/lib/public -m32 -shared /home/meep/git/gluabuild/source-sdk-2013/mp/src/lib/public/linux32/libtier0.so /home/meep/git/gluabuild/source-sdk-2013/mp/src/lib/public/linux32/tier1.a /home/meep/git/gluabuild/source-sdk-2013/mp/src/lib/public/linux32/tier2.a /home/meep/git/gluabuild/source-sdk-2013/mp/src/lib/public/linux32/tier3.a /home/meep/git/gluabuild/source-sdk-2013/mp/src/lib/public/linux32/mathlib.a -Wl,-z,defs -std=c++11
  LINKCMD = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	strip --keep-file-symbols --strip-debug -p ../../bin/gm_roc_linux.dll
  endef
all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/VPTR.o \
	$(OBJDIR)/VTable.o \
	$(OBJDIR)/luaInterface.o \
	$(OBJDIR)/interface.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/proc.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES) ${CUSTOMFILES}
	@echo Linking roc
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning roc
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH)
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/VPTR.o: ../../includes/Hook/VPTR.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VTable.o: ../../includes/Hook/VTable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/luaInterface.o: ../../includes/luaInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/interface.o: ../../src/interface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: ../../src/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/proc.o: ../../src/proc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif
